In [19]:
!pip install joblib
!pip install seaborn

import os
import joblib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

plt.style.use("fivethirtyeight")

  Using cached seaborn-0.11.2-py3-none-any.whl (292 kB)
  Using cached scipy-1.7.3-cp37-cp37m-win_amd64.whl (34.1 MB)


In [4]:
np.random.randn(3) * 1e-4

array([ 4.58515235e-05, -1.27117830e-04,  1.52119441e-05])

In [62]:
class Perceptron:
    def __init__(self, eta: float=None, epochs: int=None):
        self.weights = np.random.randn(3) * 1e-4
        self.epochs = epochs
        self.eta = eta
        
    def _z_outcome(self, inputs, weights):
        return np.dot(inputs, weights)
    
    def activation_function(self, z):
        return np.where(z > 0, 1, 0)
    
    def fit(self, X, y):
        self.X = X
        self.y = y
        
        X_with_bias = np.hstack((self.X, -np.ones((len(self.X),1))))
        print(f"X with bias: \n{X_with_bias}")
        
        for i in range(self.epochs):
            print("--"*10)
            print(f"for epoch >> {i + 1}")
            print("--"*10)
            
            z = self._z_outcome(X_with_bias, self.weights)
            y_hat = self.activation_function(z)
            print(f"predicted value after forward pass: \n{y_hat}")
            
            error = self.y - y_hat
            print(f"error: \n{error}")
            
            self.weights = self.weights + self.eta*(np.dot(X_with_bias.T,error))
            print(f"updated weights after epoch: {i + 1}/{self.epochs}: \n{self.weights}")
            print(f"##"*10)
            
    def predict(self, X):
        X_with_bias = np.hstack((X, -np.ones((len(X),1))))
        z = self._z_outcome(X_with_bias, self.weights)
        y_hat = self.activation_function(z)
        return y_hat

In [63]:
OR = {
    'x1': [0,0,1,1],
    'x2': [0,1,0,1],
    'y' : [0,1,1,1] 
}

df_or = pd.DataFrame(OR)
df_or

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [64]:
X = df_or.drop(columns=['y'])
y = df_or.y

In [65]:
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [66]:
y

0    0
1    1
2    1
3    1
Name: y, dtype: int64

In [67]:
eta = 0.1
epochs = 10

model = Perceptron(eta, epochs)
model.fit(X,y)

X with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch >> 1
--------------------
predicted value after forward pass: 
[0 1 0 1]
error: 
0    0
1    0
2    1
3    0
Name: y, dtype: int64
updated weights after epoch: 1/10: 
[ 0.09993805  0.00014586 -0.09995335]
####################
--------------------
for epoch >> 2
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 2/10: 
[9.99380461e-02 1.45860445e-04 4.66547098e-05]
####################
--------------------
for epoch >> 3
--------------------
predicted value after forward pass: 
[0 1 1 1]
error: 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 3/10: 
[9.99380461e-02 1.45860445e-04 4.66547098e-05]
####################
--------------------
for epoch >> 4
--------------------
predicted value after forward pass: 
[0 1 1 1]
error: 
0    0
1    0
2    0
3  

In [68]:
model.predict([[1,1]])

array([1])